services:
  open-hivemind-agent:
    image: mhand79/open-hivemind:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config:/config
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "3"
        mode: non-blocking

  open-hivemind-agent-local:
    # Profile for building with the local Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "3"
        mode: non-blocking
    profiles:
      - local
