services:
  open-hivemind-agent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config:/config
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "3"
        mode: non-blocking
